# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, blazeHtml, blazeMarkup, digestiveFunctors, text }:

cabal.mkDerivation (self: {
  pname = "digestive-functors-blaze";
  version = "0.6.0.4";
  sha256 = "04ldrbwla8gcsan8hahjgf4mzm6wz7kxhwrikqgnyv0dm45ias7c";
  buildDepends = [ blazeHtml blazeMarkup digestiveFunctors text ];
  meta = {
    homepage = "http://github.com/jaspervdj/digestive-functors";
    description = "Blaze frontend for the digestive-functors library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
