# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, digestiveFunctors, happstackServer, text }:

cabal.mkDerivation (self: {
  pname = "digestive-functors-happstack";
  version = "0.6.1.0";
  sha256 = "02akxqb8zmc4gbgs79g8k5ycp20c54zc025vl6l3b4mc45lp73r4";
  buildDepends = [ digestiveFunctors happstackServer text ];
  meta = {
    homepage = "http://github.com/jaspervdj/digestive-functors";
    description = "Happstack backend for the digestive-functors library";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
})
